### ISSUE TITLE
Notebook example unable to download data

### ISSUE THREAD

**Issue by lakka** [actris/actris-api-docs#2]
The notebook example at https://github.com/actris/actris-api-docs/blob/master/docs/notebooks/ebas.ipynb, heading _Use Thredds and opendap for fetching metadata_, fails to retrieve the file `https://thredds.nilu.no/thredds/dodsC/ebas/NO0042G.20180101000000.20190508191242.dmps.particle_number_size_distribution.pm10.1y.1h.NO01L_NILU_DMPSmodel2_ZEP.NO01L_dmps_DMPS_ZEP01.lev2.nc` with the following error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
 in 
      1 opendap_url = 'https://thredds.nilu.no/thredds/dodsC/ebas/NO0042G.20180101000000.20190508191242.dmps.particle_number_size_distribution.pm10.1y.1h.NO01L_NILU_DMPSmodel2_ZEP.NO01L_dmps_DMPS_ZEP01.lev2.nc'
----> 2 dataset = netCDF4.Dataset(opendap_url)

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -68] NetCDF: I/O failure: b'https://thredds.nilu.no/thredds/dodsC/ebas/NO0042G.20180101000000.20190508191242.dmps.particle_number_size_distribution.pm10.1y.1h.NO01L_NILU_DMPSmodel2_ZEP.NO01L_dmps_DMPS_ZEP01.lev2.nc'
```

Here is the `curl` output for the aforementioned URL:
```
Error {
    code = 400;
    message = "Unrecognized request";
};
```

Thanks!

**Comment by richard-olav** [comment]
The curl output should be okay, because the netCDF4 library is using the opendap data access protocol to fetch the data, so you would expect a "Unrecognized request".

I just tested now, and it works for me. What version of the netCDF4 are you running (mine is 1.5.3)?

Seem to be something similar here: https://github.com/Unidata/netcdf4-python/issues/753

**Comment by lakka** [comment]
Closing as this is likely a macOS-specific problem. The netCDF4 version I have is also 1.5.3. I'm running a macOS Catalina behind a proxy, and we couldn't reproduce the error on a Linux computer in the same network behind the same proxy. This hints that the problem is likely due to how macOS handles proxies. However, `ncdump` seems to be able to download the file so that's a possible workaround.
